name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  terraform:
    name : 'Terraform'
    env :
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_VALUE_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUB}}
      ARM_TENANT_ID: ${{ secrets.AZURE_DIRECTORY_ID}}
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash
    
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:
        args: ls -l
        tf_actions_version: 2.92.0
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: "./terraform"

    - name: 'Terraform init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 2.92.0
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"

    - name: 'Terraform validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 2.92.0
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./terraform"

    - name: 'Terraform apply'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 2.92.0
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./terraform"
